version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    networks:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp-volume:/var/www
    depends_on:
      - wordpress
    restart: on-failure 
    init: true

  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin", "-h", "mariadb", "-u", "root", "-p $ROOT_PASS", "ping", "-s"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - wp-volume:/var/www
    networks:
      - wordpress
    env_file: ./.env
    depends_on:
      - mariadb
    restart: on-failure 
    init: true

  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - wordpress
    env_file: ./.env
    restart: on-failure 
    init: true

volumes:
  wp-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/wp
      o: bind
  db-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/$USER/data/mariadb
      o: bind

networks:
  wordpress:
    driver: bridge